//! `jarvis-app` — developer CLI for LilithOS SDK apps.
//!
//! Two subcommands:
//!
//! ```text
//! jarvis-app new <id>           # scaffold a new app skeleton in ./<id>/
//! jarvis-app validate <path>    # parse + validate a manifest.toml
//! ```
//!
//! Keeps the SDK developer loop short: from `cargo new` -> "where do I
//! put the manifest, what's the DBus name, what's the Dispatch shape"
//! down to one command that drops a working skeleton.
//!
//! Dogfoods `jarvis_sdk_types::load_one` on the generated manifest in
//! tests so the templates can't drift from the actual schema validator.

use anyhow::{anyhow, bail, Context, Result};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    let cmd = match args.next() {
        Some(c) => c,
        None => {
            usage();
            return ExitCode::from(2);
        }
    };

    let result = match cmd.as_str() {
        "new" => match args.next() {
            Some(id) => cmd_new(&id, &std::env::current_dir().unwrap_or(PathBuf::from("."))),
            None => {
                usage();
                return ExitCode::from(2);
            }
        },
        "validate" => match args.next() {
            Some(path) => cmd_validate(Path::new(&path)),
            None => {
                usage();
                return ExitCode::from(2);
            }
        },
        "help" | "--help" | "-h" => {
            usage();
            return ExitCode::SUCCESS;
        }
        other => {
            eprintln!("unknown subcommand '{other}'");
            usage();
            return ExitCode::from(2);
        }
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::from(1)
        }
    }
}

fn usage() {
    eprintln!(
        "jarvis-app — developer CLI for LilithOS SDK apps\n\
         \n\
         usage:\n  \
           jarvis-app new <id>           Scaffold a new app skeleton in ./<id>/\n  \
           jarvis-app validate <path>    Parse + validate a manifest.toml\n"
    );
}

/// Scaffold a new SDK app under `parent/<id>/`. Fails when the directory
/// already exists — won't silently overwrite a user's work.
pub fn cmd_new(id: &str, parent: &Path) -> Result<()> {
    // Validate the id against the same regex the Action Bus uses, but
    // without touching the filesystem — we don't want to risk colliding
    // with anything the user already has on disk.
    if !jarvis_sdk_types::is_valid_app_id(id) {
        return Err(anyhow!(
            "invalid app id '{id}' (must match ^[a-z][a-z0-9_]*$)"
        ));
    }

    let dir = parent.join(id);
    if dir.exists() {
        bail!("'{}' already exists; refusing to overwrite", dir.display());
    }
    std::fs::create_dir_all(dir.join("src")).context("create app dir")?;

    std::fs::write(dir.join("Cargo.toml"), cargo_template(id)).context("write Cargo.toml")?;
    std::fs::write(dir.join("src").join("main.rs"), main_rs_template(id))
        .context("write src/main.rs")?;
    std::fs::write(dir.join("manifest.toml"), manifest_template(id))
        .context("write manifest.toml")?;
    std::fs::write(dir.join("README.md"), readme_template(id)).context("write README.md")?;

    eprintln!("✓ Scaffolded {} at {}", id, dir.display());
    eprintln!();
    eprintln!("next:");
    eprintln!("  cd {id}");
    eprintln!("  cargo build --release");
    eprintln!("  sudo install -m 0755 target/release/{id} /usr/bin/{id}");
    eprintln!("  sudo install -Dm0644 manifest.toml /usr/share/jarvis/apps/{id}/manifest.toml");
    eprintln!("  systemctl --user restart jarvis-action-bus");
    eprintln!();
    eprintln!("then ask Lilith to call {id}.hello");
    Ok(())
}

pub fn cmd_validate(path: &Path) -> Result<()> {
    let manifest =
        jarvis_sdk_types::load_one(path).with_context(|| format!("validate {}", path.display()))?;
    println!(
        "✓ {} — id={} actions={}",
        path.display(),
        manifest.app.id,
        manifest.actions.len()
    );
    for action in &manifest.actions {
        println!("    - {}", action.name);
    }
    Ok(())
}

fn cargo_template(id: &str) -> String {
    format!(
        r#"[package]
name = "{id}"
version = "0.1.0"
edition = "2021"
description = "LilithOS SDK app — generated by jarvis-app new"

[[bin]]
name = "{id}"
path = "src/main.rs"

[dependencies]
anyhow             = "1"
serde              = {{ version = "1", features = ["derive"] }}
serde_json         = "1"
tokio              = {{ version = "1", features = ["rt-multi-thread", "macros"] }}
tracing            = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter"] }}
zbus               = {{ version = "4", features = ["tokio"] }}
"#
    )
}

fn main_rs_template(id: &str) -> String {
    format!(
        r#"//! `{id}` — generated by `jarvis-app new`.
//!
//! Hosts `com.jarvis.app.{id}` on the session bus and implements one
//! demo action (`{id}.hello`). Add more by extending the match arms in
//! `dispatch`.

use serde_json::{{json, Value}};
use zbus::{{connection, interface}};

struct App;

#[interface(name = "com.jarvis.app.{id}")]
impl App {{
    /// Action Bus contract: `Dispatch(action, params_json) -> string`.
    /// Returns a JSON envelope: `{{ result }}` on success, `{{ error }}` on failure.
    async fn dispatch(&self, action: &str, params_json: &str) -> String {{
        let params: Value = serde_json::from_str(params_json).unwrap_or(Value::Null);
        let outcome = match action {{
            "{id}.hello" => hello(&params),
            other => Err(format!("unknown action: {{other}}")),
        }};
        match outcome {{
            Ok(value) => json!({{ "result": value }}).to_string(),
            Err(message) => json!({{
                "error": {{ "code": "execution_failed", "message": message }}
            }}).to_string(),
        }}
    }}
}}

fn hello(params: &Value) -> Result<Value, String> {{
    let name = params
        .get("name")
        .and_then(|v| v.as_str())
        .unwrap_or("world");
    Ok(json!({{ "greeting": format!("Hello, {{name}}!") }}))
}}

#[tokio::main]
async fn main() -> anyhow::Result<()> {{
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("{id}=info".parse()?),
        )
        .init();

    tracing::info!("Starting {id}");

    let _conn = connection::Builder::session()?
        .name("com.jarvis.app.{id}")?
        .serve_at("/com/jarvis/app/{id}", App)?
        .build()
        .await?;

    tracing::info!("Ready on com.jarvis.app.{id}");

    loop {{
        tokio::time::sleep(std::time::Duration::from_secs(3600)).await;
    }}
}}
"#
    )
}

fn manifest_template(id: &str) -> String {
    format!(
        r#"# Jarvis SDK manifest.
#
# Install at /usr/share/jarvis/apps/{id}/manifest.toml so the Action Bus
# picks it up at startup. The directory name must equal `app.id`.

[app]
id          = "{id}"
name        = "{id}"
version     = "0.1.0"
description = "Generated by jarvis-app new"
exec        = "/usr/bin/{id}"

[[actions]]
name        = "{id}.hello"
description = "Say hello. Replace this with your real action."
[actions.schema]
type     = "object"
[actions.schema.properties.name]
type = "string"
"#
    )
}

fn readme_template(id: &str) -> String {
    format!(
        r#"# {id}

LilithOS SDK app scaffolded by `jarvis-app new`.

## Build + install

```bash
cargo build --release
sudo install -m 0755 target/release/{id} /usr/bin/{id}
sudo install -Dm0644 manifest.toml /usr/share/jarvis/apps/{id}/manifest.toml

# A DBus service file lets the Action Bus auto-activate the app on
# first call. Optional but recommended.
sudo install -Dm0644 /dev/stdin /usr/share/dbus-1/services/com.jarvis.app.{id}.service <<'EOF'
[D-BUS Service]
Name=com.jarvis.app.{id}
Exec=/usr/bin/{id}
EOF

systemctl --user restart jarvis-action-bus
```

## Try it

Ask Lilith to call `{id}.hello`. The default implementation returns
`Hello, world!` — replace `hello()` in `src/main.rs` with whatever
your app actually does.

## Adding more actions

1. Add an entry to `manifest.toml` under `[[actions]]`. Names must start
   with `{id}.` — the Action Bus rejects manifests that violate this.
2. Add a match arm in `dispatch()` in `src/main.rs`.
3. Rebuild + reinstall + restart `jarvis-action-bus`.
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_scaffolds_a_valid_manifest() {
        let dir = tempfile::tempdir().unwrap();
        cmd_new("demoapp", dir.path()).expect("scaffold");

        // Files exist
        let root = dir.path().join("demoapp");
        assert!(root.join("Cargo.toml").exists());
        assert!(root.join("src/main.rs").exists());
        assert!(root.join("manifest.toml").exists());
        assert!(root.join("README.md").exists());

        // The generated manifest passes the real validator. If templates
        // drift from sdk-types' rules, this fails immediately.
        let manifest =
            jarvis_sdk_types::load_one(&root.join("manifest.toml")).expect("manifest validates");
        assert_eq!(manifest.app.id, "demoapp");
        assert_eq!(manifest.actions.len(), 1);
        assert_eq!(manifest.actions[0].name, "demoapp.hello");
    }

    #[test]
    fn new_refuses_invalid_id() {
        let dir = tempfile::tempdir().unwrap();
        let err = cmd_new("Bad-ID", dir.path()).unwrap_err();
        assert!(err.to_string().contains("invalid app id"));
        // Should NOT have left a half-created directory behind.
        assert!(!dir.path().join("Bad-ID").exists());
    }

    #[test]
    fn new_refuses_existing_directory() {
        let dir = tempfile::tempdir().unwrap();
        cmd_new("first", dir.path()).unwrap();
        let err = cmd_new("first", dir.path()).unwrap_err();
        assert!(err.to_string().contains("already exists"));
    }

    #[test]
    fn validate_round_trips_a_generated_manifest() {
        let dir = tempfile::tempdir().unwrap();
        cmd_new("rtcheck", dir.path()).unwrap();
        cmd_validate(&dir.path().join("rtcheck").join("manifest.toml")).expect("validate passes");
    }
}
